default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 12345678
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_api_development
  
test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  database: todo_api_production
  username: todo_api
  password: <%= ENV["TODO_API_DATABASE_PASSWORD"] %>
